AWSTemplateFormatVersion: 2010-09-09
Description: SSL certificate

Parameters:
  HostName:
    Type: String
    Default: 'shufflify.io'

Resources:
  WildcardCertificate:
    Type: 'AWS::CertificateManager::Certificate'
    Properties:
      DomainName: !Sub '*.${HostName}'
      DomainValidationOptions:
        - DomainName: !Sub '*.${HostName}'
          ValidationDomain: !Ref HostName
  SSLCertificate:
    Type: 'AWS::CertificateManager::Certificate'
    Properties:
      DomainName: !Ref HostName
      DomainValidationOptions:
        - DomainName: !Ref HostName
          ValidationDomain: !Ref HostName

Outputs:
  TLDCertificate:
    Description: 'Certificate ARN for shufflify.io certificate'
    Value: !Ref SSLCertificate
    Export:
      Name: ShufflifyCertificate
  WildcardCertificate:
    Description: 'Certificate ARN for wildcard certificate'
    Value: !Ref WildcardCertificate
    Export:
      Name: ShufflifyWildcardCertificate
